reference_module: "src.reference"

user_modules:
  - "src.team01"
  - "src.team02"
  - "src.team03"

benchmarks:
  - function_name: "square"
    max_time: 1
    args:
      - name: "size"
        increment: "lambda x: x + 1"
        default: 1

  - function_name: "triangle"
    max_time: 1
    args:
      - name: "size"
        increment: "lambda x: x + 1"
        default: 1

  - function_name: "rhombus"
    max_time: 1
    args:
      - name: "size"
        increment: "lambda x: x + 1"
        default: 1
