reference_module: "benchmarks.reference"

user_modules:
  - "benchmarks.team01"
  - "benchmarks.team02"
  - "benchmarks.team03"

benchmarks:
  - function_name: "square"
    description: |
      **Square**: Generate a square of a given size.
      - **size**: The size of the square's sides.
    max_time: 100
    args:
      - name: "size"
        increment: "lambda x: x + 1"
        default: "int(1)"

  - function_name: "triangle"
    description: |
      **Triangle**: Generate a right-angled triangle with stars.
      - **size**: The height of the triangle.
    max_time: 100
    args:
      - name: "size"
        increment: "lambda x: x + 1"
        default: "int(1)"

  - function_name: "rhombus"
    description: |
      **Rhombus**: Create a rhombus pattern.
      - **size**: The size of the rhombus.
    max_time: 100
    args:
      - name: "size"
        increment: "lambda x: x + 1"
        default: "int(1)"

  - function_name: "running_sum"
    description: |
      **Running Sum**: Calculate the running sum of a list.
      - **nums**: The list of integers.
    max_time: 50
    args:
      - name: "size"
        increment: "lambda x: x + 1"
        default: "int(4)"
        hidden: true
      - name: "nums"
        increment: "lambda **kwargs: [random.randint(0, 100) for _ in range(kwargs['size'])]"
        default: "list([2,5,3,1])"

  - function_name: "histogram"
    description: |
      **Histogram**: Generate a histogram from a list of numbers.
      - **nums**: The list of numbers.
    max_time: 50
    args:
      - name: "size"
        increment: "lambda x: x + 1"
        default: "int(3)"
        hidden: true
      - name: "nums"
        increment: "lambda **kwargs: [random.randint(0, 10) for _ in range(kwargs['size'])]"
        default: "list([4,1,2])"

  - function_name: "scatter"
    description: |
      **Scatter**: Create a scatter plot of points.
      - **size**: The size of the scatter plot.
      - **points**: The list of points as tuples.
    max_time: 50
    args:
      - name: "x"
        increment: "lambda x: x + 1"
        default: "int(10)"
        hidden: true
      - name: "size"
        increment: "lambda **kwargs: int(kwargs['x'] ** 0.65)"
        default: "int(4)"
      - name: "points"
        increment: "lambda **kwargs: [[random.randint(1, kwargs['size']), random.randint(1, kwargs['size'])] for _ in range(random.randint(1, kwargs['size'] + 1))]"
        default: "list([[2,2],[1,3],[4,1]])"

  - function_name: "count_pairs"
    description: |
      **Count Pairs**: Count the pairs of numbers that differ by a specific value.
      - **nums**: The list of numbers.
      - **k**: The difference value.
    max_time: 50
    args:
      - name: "size"
        increment: "lambda x: x + 1"
        default: "int(4)"
        hidden: true
      - name: "nums"
        increment: "lambda **kwargs: [random.randint(0, kwargs['size'] // 2) for _ in range(kwargs['size'])]"
        default: "list([1,2,2,1])"
      - name: "k"
        increment: "lambda **kwargs: random.randint(1, kwargs['size'] // 2)"
        default: "int(1)"

  - function_name: "dividing_numbers"
    description: |
      **Dividing Numbers**: Find self-dividing numbers in a range.
      - **left**: The left boundary of the range.
      - **right**: The right boundary of the range.
    max_time: 50
    args:
      - name: "size"
        increment: "lambda x: x + 1"
        default: "int(10)"
        hidden: true
      - name: "left"
        increment: "lambda **kwargs: random.randint(0, kwargs['size'] // 2)"
        default: "int(0)"
      - name: "right"
        increment: "lambda **kwargs: random.randint(kwargs['size'] // 2, kwargs['size'])"
        default: "int(10)"

  - function_name: "generate_trajectory"
    description: |
      **Generate Trajectory**: Simulate the trajectory of a projectile.
      - **velocity**: The initial velocity of the projectile.
      - **angle**: The angle of projection.
      - **size**: The size of the simulation area.
    max_time: 50
    args:
      - name: "x"
        increment: "lambda x: x + 1"
        default: "int(25)"
        hidden: true
      - name: "velocity"
        # Use a biased random function that favors higher velocities
        increment: "lambda **kwargs: int(kwargs['x'] * (0.1 + random.random()))"
        default: "int(15)"
      - name: "angle"
        # Use a biased random function that avoids extreme angles
        increment: "lambda angle: int(45 + (random.random() - 0.5) * 45)"
        default: "int(45)"
      - name: "size"
        increment: "lambda **kwargs: [random.randint(kwargs['x'], int(kwargs['x'] * 1.5)), random.randint(kwargs['x'] // 3, kwargs['x'] // 1.5)]"
        default: "list([25, 8])"

  - function_name: "sort_by_height"
    description: |
      **Sort by Height**: Sort names by corresponding heights.
      - **names**: The list of names.
      - **heights**: The list of corresponding heights.
    max_time: 10
    args:
      - name: "x"
        increment: "lambda x: x + 1"
        default: "int(3)"
        hidden: true
      - name: "names"
        increment: "lambda **kwargs: [fake.first_name() for _ in range(kwargs['x'])]"
        default: "list(['Alice', 'Bob', 'Charlie'])"
      - name: "heights"
        increment: "lambda **kwargs: [random.randint(150, 200) for _ in range(kwargs['x'])]"
        default: "list([165, 180, 175])"

  - function_name: "best_student"
    description: |
      **Best Student**: Determine the student with the highest average grade.
      - **gradebook**: The dictionary containing student names and their grades.
    max_time: 15
    args:
      - name: "x"
        increment: "lambda x: x + 1"
        default: "int(3)"
        hidden: true
      - name: "offsets"
        increment: "lambda **kwargs: [random.randint(2, 7) for _ in range(kwargs['x'])]"
        default: "list([4, 5, 4])"
        hidden: true
      - name: "gradebook"
        increment: "lambda **kwargs: {
                      fake.first_name(): [
                        round(random.uniform(0, 3) + kwargs['offsets'][idx], 1) for _ in range(random.randint(1, int(kwargs['x'] ** 1.15 // 3 + 1)))
                      ] for idx in range(kwargs['x'])
                    }"
        default: "dict({'Alice': [8, 7.5, 8.8],'Bob': [8.5, 8, 9],'Charlie': [6, 6.2, 7.5]})"

  - function_name: "jobs_counter"
    description: |
      **Jobs Counter**: Count occurrences of each job in a list.
      - **jobs**: The list of jobs.
    max_time: 10
    args:
      - name: "x"
        increment: "lambda x: x + 1"
        default: "int(9)"
        hidden: true
      - name: "elems"
        increment: "lambda **kwargs: [fake.job() for _ in range(int(kwargs['x'] ** 0.5))]"
        default: "list(['artist', 'doctor', 'professor'])"
        hidden: true
      - name: "jobs"
        increment: "lambda **kwargs: [
                      kwargs['elems'][int(random.randint(0, len(kwargs['elems']) - 1))] for _ in range(int(kwargs['x'] ** 1.15))
                    ]"
        default: "list(['artist', 'doctor', 'artist', 'professor', 'artist', 'professor', 'professor', 'artist'])"

