reference_module: "benchmarks.reference"

user_modules:
  - "benchmarks.team01"
  - "benchmarks.team02"
  - "benchmarks.team03"

benchmarks:
  - function_name: "square"
    max_time: 100
    args:
      - name: "size"
        increment: "lambda x: x + 1"
        default: 1

  - function_name: "triangle"
    max_time: 100
    args:
      - name: "size"
        increment: "lambda x: x + 1"
        default: 1

  - function_name: "rhombus"
    max_time: 100
    args:
      - name: "size"
        increment: "lambda x: x + 1"
        default: 1
